# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writter', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('token', models.TextField()),
                ('words', models.TextField()),
            ],
        ),
    ]
